# Open Data

The School of Psychology aspires for staff to share their data where appropriate and possible.

## What is Open Data?
Making the data that underlies the inferences and conclusions in our studies available to others is an important step to promoting replicability. It allows others to check these the validity of these inferences () or to search for further patterns within the data (maximizing the usefulness of the data). [FAIR principles](https://www.go-fair.org/fair-principles/) are considered important guidance for data availability, focusing on Findability, Accessibility, Interoperability and Reuse. 

## Benefits

-	Maximizing usefulness of recorded data for public good
-	In combination with preregistration it avoids suggestions of benefiting from undisclosed flexibility

## Questions

### Should all data be shared?
No. A commonly used phrasing is “Be as open as possible, as closed as necessary”. If you cannot anonymize your data, sharing may not be needed or possible (unless explicitly consented by the participants). Moreover, sharing of data (or materials) may be constrained by considerations of intellectual property. 

### Is it extra work?
Yes. Many of the repositories require creating an account. Moreover, while uploading data nowadays typically is a drag-and-drop exercise, FAIR principles mean the data should be organized logically and accompanied by metadata. However, with data accessibility in mind, many of these aspects can be introduced early in the research cycle to minimize the time needed.

### Where to share data?
QUB offers researchers to share their research data through Pure (https://pure.qub.ac.uk/en/datasets/) 

Several online repositories are available for sharing data.

### [Research Box](https://researchbox.org)
-	Mirroring AsPredicted.org
-	Data and materials archive

### [Open Science Framework](https://osf.io)
-	Platform dedicated to Open Science.
-	Multiple server locations

### [Zenodo](https://zenodo.org)
-	Servers based at CERN
