# Education  

The QAA Subject Benchmark Statement for Psychology emphasises the importance of our students developing 'psychological literacy' ([QAA, 2019](https://www.qaa.ac.uk/docs/qaa/subject-benchmark-statements/subject-benchmark-statement-psychology.pdf?sfvrsn=6935c881_15)). According to the QAA Statement, psychological literacy includes an awareness of current debates and controversies in the discipline, appreciation of 'rigorous empirical methodology', critical analysis, and understanding of the relationships between theory and evidence. Given the accelerated discussions within our field about the standards of evidence, the reliability of theoretically consequential findings, and the move towards more Open Science practices that are motivated by these discussions, it is clear that in the present day psychological literacy should include knowledge about Open Science. It is important therefore that students on our undergraduate and postgraduate degree programmes are afforded opportunities to learn about and enact Open Science principles as part of their psychology training. 

There are already several points in our degree programmes in which the context and/or the principles of Open Science feature as part of students' education opportunities. These are described below for your awareness of what students on different programmes will be exposed to through their pathways. There are also further steps proposed in these guidelines to increase and enhance the Open Science content of our education delivery. Resources for including Open Science practices in student research projects is detailed elsewhere in these guidelines. Additional resources which have been designed for educational purposes can be found [here](https://psyarxiv.com/fgv79). 

## Where is there Open Science education in current programmes? 

### BSc (Hons) Psychology 

Level 2 Core Psychology -- the 'replication crisis' and open science measures in response are covered over three lecture hours as part of Conceptual Issues (typically part of assessment in exam questions) 

Level 3 thesis -- some supervisors encourage thesis students to pre-register projects and/or run replication studies 

### MSc Psychological Science 

Core Psychology -- the 'replication crisis' and open science measures in response are covered over three lecture hours as part of Conceptual Issues (typically part of assessment in exam questions) 

Thesis module-- some supervisors encourage thesis students to pre-register projects and/or run replication studies 

### MSc Clinical Health / Applied Developmental Psychology (/ PGR / DECAP? / DClin) 

Research Skills -- The principles, context and practices of Open Science are thoroughly covered throughout this module (100% assessment -- pre-registration assignment) 

## Where could Open Science education be expanded / reinforced in current programmes? 

### BSc (Hons) Psychology 

Level 2 Psychological Methods -- encourage pre-registration and/or replication studies for Level 2 group research projects 

Level 3 thesis -- encourage pre-registration and/or (conceptual) replication studies and/or meta-analyses for thesis projects; thesis marking criteria to include considerations of how/whether thesis reports demonstrate open science principles in design and reporting of thesis (e.g., transparency of evidence, steps taken to avoid HARKing, actions taken to guard against QRPs). 

### MSc Psychological Science 

Methods, Design, and Analysis in Psychology -- encourage pre-registration and/or replication studies for tutorial group projects 

Thesis module -- encourage pre-registration and/or (conceptual) replication studies and/or meta-analyses for thesis projects; thesis marking criteria to include considerations of how/whether thesis reports demonstrate open science principles in design and reporting of thesis (e.g., transparency of evidence, steps taken to avoid HARKing, actions taken to guard against QRPs) 

### Doctorates

Doctoral supervisors increasingly support students in embedding open science practices into their workflows. This includes [pre-registering studies](https://qubpsy.github.io/QUBPsyOpenScience/preregistration.html) where appropriate, obtaining [participant consent to share anonymised data](https://qubpsy.github.io/QUBPsyOpenScience/ethics.html), and [making available research data](https://qubpsy.github.io/QUBPsyOpenScience/open_data.html), [analytic code, research protocols, and other materials](https://qubpsy.github.io/QUBPsyOpenScience/open_materials.html) via open repositories. Students are advised to consult their supervisors and keep in mind that sharing data and materials may be required by examiners. With Queen’s endorsement of the [*thesis with publication* model](https://www.qub.ac.uk/directorates/AcademicStudentAffairs/AcademicAffairs/ResearchDegreeProgrammes/Assessment/TWP/), creating a central project page (e.g., on the Open Science Framework) offers several advantages. For instance, it allows students to organise pre-registrations, data, and code from all PhD studies into components or sub-folders within a single project, and share one unified link in their thesis (See the [Open Science Framework project FAQ](https://help.osf.io/article/553-project-and-components-faq-s) for more details). Importantly, these practices are not limited to users of R or other programming languages.

### All programmes 

Making project data openly available through a data repository (e.g., OSF). 

Pre-registration of research protocols for projects (e.g., OSF, AsPredicted). 

Shift to teaching analysis using openly accessible and reproducible data analysis software packages (R with R Markdown, Python with Jupyter, Quarto etc). 
