# Principles  {#Principles .unnumbered}

These guidelines will support staff of the School of Psychology, Queen's University Belfast, in their efforts to engage in Open Science practices, now considered to be at the cutting edge of our discipline. We aim to inspire staff to engage with Open Science; we should all aspire to adopt Open Science practices. Over time, these may well become requirements (e.g., from publishers, funders, REF), but it makes sense to anticipate this. These guidelines and Open Science in general are governed by several principles. 

## Kindness 

These Open Science guidelines are written as an accessible guide to Open Science for academic and research staff in the School of Psychology. However, they should also be helpful for professional service staff and students. In the spirit of Open Science, the guidelines are available for all including those from outside the institution. The following guide is a living document, which will be continually updated to keep the information aligned with advances in Open Science, so it is best to refer to the most current version of the guidelines. 

## Equity and Diversity 

Open Science emphasises transparency and integrity in accurate and truthful reporting of science. Being open and transparent at all stages and all levels of the scientific process improves all scientific fields. The principles and proposed practices of Open Science serve to expand the accessibility and inclusivity of research and the knowledge it creates. By making data, analysis methods, and other research materials available to all through online repositories, many of the barriers to participation in science for those outside of elite academic institutions are removed. In this sense, Open Science principles are aligned to enhancing equity in science and expanding the diversity of future research as a result. 

## Why is Open Science important? 

Open Science directly addresses the 'replication crisis' initially identified in the field of Psychology. The replication crisis happened because scientists  were incentivised (by the academic reward structure) to report results that often failed to replicate (e.g., 'false positives'). Open Science is a mindset to do what is right for science, to strive for  

\- transparency of motivations, methods and inferences  

\- reproducibility of scientific methods  

\- robustness of patterns (i.e., replicability) 

Open Science emphasises transparency and integrity in accurate and truthful reporting of science. Being open and transparent at all stages and all levels of the scientific process improves all scientific fields.  

There is an increasing recognition of the value of Open Science practices proposed to fulfil these aims. Indeed, engagement with Open Science is being embedded in criteria for 1) open access publishing in high impact journals, 2) research funding, especially by national and international funders 3) the Research Excellent Framework, 4) academic job descriptions and progression and 5) Higher Education teaching curricula. 

## Open Science Practices 

To help embed Open Science within the research culture of the School of Psychology, this guide will provide descriptions and practical advice on key Open Science practices: [Preregistration](https://qubpsy.github.io/QUBPsyOpenScience/preregistration.html), [Ethics and Open Science](https://qubpsy.github.io/QUBPsyOpenScience/ethics.html), [Open data](https://qubpsy.github.io/QUBPsyOpenScience/open_data.html), [Open materials](https://qubpsy.github.io/QUBPsyOpenScience/open_materials.html), [Open-source formats](https://qubpsy.github.io/QUBPsyOpenScience/open_source_formats.html), [Reproducible Documents](https://qubpsy.github.io/QUBPsyOpenScience/reproducible_documents.html), [Open-Access Publishing](https://qubpsy.github.io/QUBPsyOpenScience/open-access_publishing.html) and [Education](https://qubpsy.github.io/QUBPsyOpenScience/education.html). 

## Feedback and additional information 

This document is written by your colleagues to support the School's efforts to be more engaged in open science practices. If you spot any errors, would like to add any amendments, or have an innovation or efficient practice to share, please fill out the [Open Science Webform](https://qubpsyopensciencewebform.formr.org).

If you require any advice or support regarding your Open Science practice feel free to contact the authors at 

Joost Dessing [j.dessing\@qub.ac.uk](mailto:j.dessing@qub.ac.uk) 

Lisa Graham-Wisener [l.grahamwisener\@qub.ac.uk](mailto:l.grahamwisener@qub.ac.uk)  

Gary McKeown [g.mckeown\@qub.ac.uk](mailto:g.mckeown@qub.ac.uk)  

Paul Toner [p.toner\@qub.ac.uk](mailto:p.toner@qub.ac.uk)  

Martin Robinson [p.toner\@qub.ac.uk](mailto:Martin.Robinson@qub.ac.uk)

Martin Robinson [p.toner\@qub.ac.uk](mailto:Martin.Robinson@qub.ac.uk)

Bethan Iley [biley01\@qub.ac.uk](mailto:biley01@qub.ac.uk)

Matthew Rodger [m.rodger\@qub.ac.uk](mailto:m.rodgers@qub.ac.uk) 

Gillian Shorter [g.shorter\@qub.ac.uk](mailto:g.shorter@qub.ac.uk) 

Tanja Gerlach [t.gerlach\@qub.ac.uk](mailto:t.gerlach@qub.ac.uk) 

Thomas Schultze-Gerlach [t.schultze\@qub.ac.uk](mailto:t.schultze@qub.ac.uk) 
