# Open-Access Publishing

**We encourage staff to publish open-access where possible and appropriate to do so** 

## What is Open-access Publishing?

Open Access publishing refers to making research publications freely available to anyone who would want to access them, including the public. Traditionally, access to publications has been hidden behind a publisher paywall, meaning access is limited to those with a library subscription or those who can afford the access fee. By publishing open access, any financial, legal, and technical barriers to accessing a publication are removed. There are different levels of open access publishing.

[Open Access publishing includes Green, Gold, and Diamond pathways](https://open-access.network/en/information/open-access-primers/green-and-gold) that refers to publishing in a traditional journal and sharing a version of the article (generally a preprint or postprint) in a subject or institutional repository. Green Open Access includes making previously published works freely available, Gold Open Access ss refers to the publishing works in a format free to readers, whereas Diamond Open Access is entirely free in dissemination: for authors and readers.

## Benefits

-   Maximising the international visibility and reach of research, across both High-Income and Low-to-Middle-Income countries

-   Maximising the usefulness and impact of research to influence policy and practice

-   Maximising the value of publicly funded research to the taxpayer

## Where to publish open access?

The Open Research team are available to advise on all aspects of open access publishing (<https://libguides.qub.ac.uk/openaccess/introduction>) and have several open access agreements with publishers, e.g. a fee waiver for [Gold open access publishing](https://libguides.qub.ac.uk/openaccess/Gold) with journals.

If you are not publishing in a Gold open access journal, QUB encourages researchers to share their publications at the earliest opportunity following publication. The nature of what is deposited and when this can be shared will depend on the publisher. The Sherpa Romeo link below provides guidance on what you need to make available.

[**CORE**](https://core.ac.uk/)

-   The largest aggregator of open access research papers in the world

[**Directory of Open Access Journals (DOAJ)**](https://www.doaj.org/)

-   A directory of Open Access Journals

[**PsyArxiv**](https://psyarxiv.com/)

-   A free preprint service for the psychological sciences

[**Sherpa Romeo**](https://v2.sherpa.ac.uk/romeo/)

An online resource that provides summaries of publisher copyright and open access archiving policies on a journal-by-journal basis. It will also provide information on whether your journal supports pre-prints and what version of the manuscript is supported for PURE deposits.

## Common Questions

*Should all publications be open access?*

Increasingly, research funders (e.g., UKRI) require publications to be open access and articles are also required to be open access for REF eligibility. If deciding not to publish open access, it is worth taking this into consideration. Ultimately it is important that your work appears before the most appropriate audience.

*Is it extra work?*

Yes and no. The decision to publish open access can be incorporated into your decision-making process on where to publish. If publishing Green open access, there is a small amount of work involved in uploading the appropriate document version to a repository.  If you are unsure of where to publish it might be useful to use the a search engine such as [Jane](https://jane.biosemantics.org/) to narrow the field and/or seek advice.
